import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Sidebar} from "@/components/sidebar";
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Sidebar />

        <main className="ml-[320px] mt-4">
          <Toaster />
          {children}
        </main>
        
      </body>
    </html>
  );
}
